Dev
shhift/my_news_prog pull request #1
Opened 2024-03-21 15:04 UTC by shhift

2024-03-21 17:31 UTC, udevgeektutor approved these changes

2024-03-28 16:11 UTC, udevgeektutor requested changes

2024-03-28 16:11 UTC, udevgeektutor commented on mywebsite/news/templates/news/base.html
> +<html>
Зачем?
Строка 5 делает тоже самое.
```suggestion
```

2024-03-28 16:23 UTC, shhift commented on mywebsite/news/templates/news/base.html
> +<html>
когда убираю строку, подсвечивает красным  <!DOCTYPE html>

2024-03-28 16:23 UTC, shhift commented on mywebsite/news/templates/news/base.html
> +<html>
<!DOCTYPE html>

2024-03-28 16:24 UTC, shhift commented on mywebsite/news/templates/news/base.html
> +<html>
'<!DOCTYPE html>'

2024-03-28 16:24 UTC, shhift commented on mywebsite/news/templates/news/base.html
> +<html>
не отправляеся то ,что я хочу, подсвечивает 4 строку

2024-03-28 16:26 UTC, udevgeektutor requested changes

2024-03-28 16:26 UTC, udevgeektutor commented on mywebsite/news/templates/news/base.html
>      <title>{% block title %}{% endblock%}</title>
лучше так
```suggestion
    <title>{% block title %}{% endblock %}</title>
```

2024-03-28 16:30 UTC, udevgeektutor commented on mywebsite/news/templates/news/base.html
> +<html>
Сконфигурируй свою IDE. Вероятно она не настроена на работу с HTML, по этому и подчёркивает.

2024-03-28 16:36 UTC, udevgeektutor requested changes

2024-03-28 16:36 UTC, udevgeektutor commented on mywebsite/mywebsite/urls.py
>  from django.contrib import admin
```suggestion
```

Импорт не используется, соответсвенно строки этой быть не должно.

2024-03-28 16:41 UTC, udevgeektutor requested changes

2024-03-28 16:41 UTC, udevgeektutor commented on mywebsite/news/static/css/styles.css
Прогони файл форматтером. в VS Code это Shift+Alft+F и файл будет легче читаться.

2024-03-28 16:41 UTC, udevgeektutor commented on mywebsite/news/templates/news/base.html
> +
```suggestion

```
ЛУчше оставить 0 или 1 строку,

2024-03-28 16:42 UTC, udevgeektutor commented
Вообще лучше все html файлы прогони форматтером. в VS Code это Shift+Alft+F и файлы будут легче читаться, не придется сидеть и ставить отступы руками.

2024-03-28 17:50 UTC, udevgeektutor requested changes

2024-03-28 17:50 UTC, udevgeektutor commented on mywebsite/news/models.py
>      def __str__(self):
Между методами должна быть 1 пустая строка.
```suggestion
        return reverse("news:article_detail", args=[self.id])
        
    def __str__(self):
```

2024-04-02 15:33 UTC, udevgeektutor reviewed
OK

2024-04-02 15:34 UTC, merged